<?php
const API_URL = "https://ybozp.dev-trackergo.adsbridge.com/extapismart/";  // domain of your offer link in your imonetizeit profile, example "https://bejwq.imitrk5.net/pixel/"
const API_KEY = "2bc352c4b539797a949fe61dc4142f533dfe2304a351ed78f338f2e0f0cd2460"; //Api key from your imonetizeit profile settings, example 54n6283a5015679c4bcd430999c88e81fb1h41e0e42e6kjh7a0792b766b83fb9
const API_CLIENT_ID = 59; //Id of your imonetizeit profile, example 42656
const HASH = "46ad2eefd2f9af05"; // Hash within your offer url, generated by imonetizeit, example "2bbd854322e8535f"
const API_CAMPAIGN_ID = 3844;

$args = [
    'api_key' => API_KEY,
    'client_id' => API_CLIENT_ID,
    'hash' => HASH,
    'campaign_id' => API_CAMPAIGN_ID,

    // requared
    'email' => !empty($_POST['email']) ? $_POST['email'] : "",
    'password' => !empty($_POST['password']) ? $_POST['password'] : "",
    'ip' => !empty($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : "",
    'ua' => !empty($_POST['ua']) ? $_POST['ua'] : $_SERVER['HTTP_USER_AGENT'],

    // not requared
    'name' => !empty($_POST['username']) ? $_POST['username'] : "",
    'gender' => !empty($_POST['gender']) ? $_POST['gender'] : "male", // male/female
    'search_gender' => !empty($_POST['search_gender']) ? $_POST['search_gender'] : "female", // male/female
    'orientation' => !empty($_POST['orientation']) ? $_POST['orientation'] : "getero", // getero/homo
    'age' => !empty($_POST['age']) ? $_POST['age'] : "",
    'country' => !empty($_POST['country']) ? $_POST['country'] : "", // iso2
    'lang' => !empty($_POST['language']) ? $_POST['language'] : "en",
    'os' => !empty($_POST['os']) ? $_POST['os'] : "", // os without version
    'device' => !empty($_POST['device']) ? $_POST['device'] : "", // mobile, tablet, desctop
];

$curl = curl_init();
curl_setopt_array($curl, [
    CURLOPT_URL => API_URL,
    CURLOPT_ENCODING => '',
    CURLOPT_CUSTOMREQUEST => 'POST',
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_POSTFIELDS => json_encode($args),
    CURLOPT_USERAGENT => !empty($_SERVER['HTTP_USER_AGENT']) ? $_SERVER['HTTP_USER_AGENT'] : "",
    CURLOPT_HTTPHEADER => array(
        'Content-Type: application/json',
        'Accept: application/json'
    ),
]);
$res = curl_exec($curl);
curl_close($curl);

header('Content-type: application/json');
echo $res;